spring:
  datasource:
    initialization-mode: always
  main:
    banner-mode: 'off'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
  profiles:
    active: 'prod'
logging:
  level:
    org:
      springframework: ERROR
weather:
  api:
    url: 'http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}'