spring:
  datasource:
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://localhost:5432/testDb
    password: password
  main:
    banner-mode: 'off'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: ERROR
weather:
  api:
    url: 'http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}'
    appid: '0e9796030b4b8a3c9e6e146047762c0a'