spring:
  datasource:
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://localhost:5432/testDb
    password: password
  main:
    banner-mode: 'off'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      springframework: ERROR